---
- name: 'Apt: Update Repositories'
  apt:  update_cache=yes cache_valid_time=3600

# This will break VMWare Tools, which will need to be recompiled.
#- name: 'Update: apt safe-upgrade'
#  apt: upgrade=safe

- name: 'build-essential: Present'
  apt: pkg=build-essential state=latest

- name: 'git: Present'
  apt: pkg=git state=latest

- name: 'ntp: Present'
  apt: pkg=ntp state=present

  # Required for apt_repository
- name: 'Apt: Present python-software-properties'
  apt:  pkg='python-software-properties' state=present

#- name: 'Configure: SSH requires key based login'
#  lineinfile: dest=/etc/ssh/sshd_config
#              regexp="PasswordAuthentication"
#              line="PasswordAuthentication no"
#  notify: 'Restart SSH'
