--- 
- name: 'haproxy: Add PPA'
  apt_repository: repo=ppa:vbernat/haproxy-1.4 state=present
  tags: haproxy

- name: 'haproxy: Present'
  apt: pkg=haproxy={{ haproxy_version }} state=present
  tags: haproxy

- name: 'haproxy: Started'
  service: name=haproxy state=started 
  tags: haproxy

- name: 'haproxy: Configuration present'
  action: template src=roles/haproxy/templates/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg mode=0640 owner=root group=root
  notify:
    - Restart haproxy
  tags: haproxy

- name: 'Sets default starting flag to 1'
  action: lineinfile dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
  notify:
    - Restart haproxy 
  tags: haproxy

- name: 'haproxy: Started'
  service: name=haproxy state=started 
  tags: haproxy
